name: flutter_search_engine
description: A web search engine built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  go_router: ^3.1.1
  json_annotation: ^4.5.0
  logger: ^1.1.0
  provider: ^6.0.3
  url_launcher: ^6.1.3

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  lint: ^1.8.2

flutter:
  uses-material-design: true